# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [cn]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        working-directory: ./website
        run: |
          yarn install
          node fetchSupporters.js

      - name: Build
        working-directory: ./website
        run: |
          yarn build

      - name: Grant Permission
        working-directory: ./website
        run: |
          sudo -i
          sudo chown -R $USER ./build

      - name: Docschina Github Action
        id: deployStatic
        uses: lcxfs1991/docschina-actions@master
        with:
          skipFiles: ${{ secrets.SKIP_FILES }}
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          staticSrcPath: ./website/build/jest
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}
